apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clickhouse-config
  labels:
    app: {{ .Release.Name }}-clickhouse
data:
  user_logging.xml: |
    <clickhouse>
      <profiles>
        <default>
          <log_queries>0</log_queries>
          <log_query_threads>0</log_query_threads>
        </default>
      </profiles>
    </clickhouse>
  enable_json.xml: |
    <clickhouse>
        <settings>
            <enable_json_type>1</enable_json_type>
        </settings>
    </clickhouse>
  logging_rules.xml: |
    <clickhouse>
      <logger>
          <level>warning</level>
          <console>true</console>
      </logger>
      <query_thread_log remove="remove"/>
      <query_log remove="remove"/>
      <text_log remove="remove"/>
      <trace_log remove="remove"/>
      <metric_log remove="remove"/>
      <asynchronous_metric_log remove="remove"/>
      <session_log remove="remove"/>
      <part_log remove="remove"/>
    </clickhouse>
  network.xml: |
    <clickhouse>
        <listen_host>0.0.0.0</listen_host>
    </clickhouse> 