{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "rybbit-secrets") -}}
{{- $hasExistingSecret := and $existingSecret (hasKey $existingSecret "data") -}}
apiVersion: v1
kind: Secret
metadata:
  name: rybbit-secrets
  labels:
    app: {{ .Release.Name }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  postgres-password: {{ if .Values.postgres.password }}{{ .Values.postgres.password | b64enc | quote }}{{ else if $hasExistingSecret }}{{ index $existingSecret.data "postgres-password" }}{{ else }}{{ include "rybbit.randomPassword" . | b64enc | quote }}{{ end }}
  postgres-user: {{ .Values.postgres.user | default "frog" | b64enc | quote }}
  clickhouse-password: {{ if .Values.clickhouse.password }}{{ .Values.clickhouse.password | b64enc | quote }}{{ else if $hasExistingSecret }}{{ index $existingSecret.data "clickhouse-password" }}{{ else }}{{ include "rybbit.randomPassword" . | b64enc | quote }}{{ end }}
  clickhouse-user: {{ .Values.clickhouse.user | default "default" | b64enc | quote }}
  better-auth-secret: {{ if .Values.backend.env.BETTER_AUTH_SECRET }}{{ .Values.backend.env.BETTER_AUTH_SECRET | b64enc | quote }}{{ else if $hasExistingSecret }}{{ index $existingSecret.data "better-auth-secret" }}{{ else }}{{ include "rybbit.randomString" . | b64enc | quote }}{{ end }} 