name: Client Build

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: "recursive"
          shallow-submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install
        working-directory: ./client

      - name: Build Next.js App
        run: npm run build
        working-directory: ./client
