name: Docker Publish

on:
  push:
    tags: ["v*"]

jobs:
  build-and-push:

    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-22.04
          - platform: linux/arm64
            runner: ubuntu-22.04-arm

    runs-on: ${{ matrix.runner || 'ubuntu-22.04' }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker - Backend
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          # Images will be ghcr.io/rybbit-io/rybbit-backend
          images: ghcr.io/${{ github.repository_owner }}/rybbit-backend
          tags: |
            type=ref,event=branch  # Creates tag like :master
            type=sha               # Creates tag like :<commit_sha_short>
            # Tags 'master' branch pushes additionally with 'latest'
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server #
          file: ./server/Dockerfile
          push: true
          platforms: ${{ matrix.platform }}   # linux/amd64 or linux/arm64
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}
          # # Optional: Enable build cache for potentially faster builds
          # cache-from: type=gha,scope=${{ github.workflow }}-backend
          # cache-to: type=gha,scope=${{ github.workflow }}-backend,mode=max

      - name: Extract metadata (tags, labels) for Docker - Client
        id: meta_client
        uses: docker/metadata-action@v5
        with:
          # Images will be ghcr.io/rybbit-io/rybbit-client
          images: ghcr.io/${{ github.repository_owner }}/rybbit-client
          tags: |
            type=ref,event=branch
            type=sha
            # Tags 'master' branch pushes additionally with 'latest'
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}

      - name: Build and push Client Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          platforms: ${{ matrix.platform }}   # linux/amd64 or linux/arm64
          tags: ${{ steps.meta_client.outputs.tags }}
          labels: ${{ steps.meta_client.outputs.labels }}
          # # Optional: Enable build cache for potentially faster builds
          # cache-from: type=gha,scope=${{ github.workflow }}-client
          # cache-to: type=gha,scope=${{ github.workflow }}-client,mode=max
